name: Terraform Deploy

on:
  push:
    branches: [ main, develop, staging ]

env:
  TF_VERSION: '1.6.0'
  AZURE_CLI_VERSION: '2.50.0'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    
    - name: Generate terraform.tfvars
      run: |
        terraform init
