name: Teszt munkafolyamat
on:
  push:
    branches:
      - '**'
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Teszt munkafolyamat

        run: |
          echo "Teszt munkafolyamat"
          terraform init
